# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci
# IP: The module: 'drom_pcie_cfgspace_writemask' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'drom_pcie_cfgspace_writemask'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci
# IP: The module: 'drom_pcie_cfgspace_writemask' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'drom_pcie_cfgspace_writemask'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
