# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci
# IP: The module: 'fifo_34_34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci
# IP: The module: 'fifo_34_34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
