# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci
# IP: The module: 'fifo_74_74_clk1_bar_rd1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_74_74_clk1_bar_rd1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_74_74_clk1_bar_rd1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci
# IP: The module: 'fifo_74_74_clk1_bar_rd1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_74_74_clk1_bar_rd1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_74_74_clk1_bar_rd1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
