# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci
# IP: The module: 'fifo_141_141_clk1_bar_wr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci
# IP: The module: 'fifo_141_141_clk1_bar_wr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
