# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci
# IP: The module: 'fifo_129_129_clk1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_129_129_clk1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_129_129_clk1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci
# IP: The module: 'fifo_129_129_clk1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_129_129_clk1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/EnigmaX1/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_129_129_clk1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
