set_property SRC_FILE_INFO {cfile:{c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc} rfile:../../../pcileech_enigma_x1.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc id:1 order:EARLY scoped_inst:i_pcileech_pcie_a7/i_pcie_7x_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.srcs/constrs_1/imports/src/pcileech_enigma_x1.xdc} rfile:../../../pcileech_enigma_x1.srcs/constrs_1/imports/src/pcileech_enigma_x1.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc} rfile:../../../pcileech_enigma_x1.srcs/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc id:3 order:LATE scoped_inst:i_pcileech_pcie_a7/i_pcie_7x_0/inst} [current_design]
current_instance i_pcileech_pcie_a7/i_pcie_7x_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_COMMON_X0Y1 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].pipe_quad.gt_common_enabled.gt_common_int.gt_common_i/qpll_wrapper_i/gtp_common.gtpe2_common_i}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X0Y0 [get_cells inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X2Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y37 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y34 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y33 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y32 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y31 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20  [get_ports ft601_be[0]]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19  [get_ports ft601_be[1]]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20  [get_ports ft601_be[2]]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports ft601_be[3]]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20  [get_ports ft601_data[0]]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22  [get_ports ft601_data[1]]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21  [get_ports ft601_data[2]]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22  [get_ports ft601_data[3]]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21  [get_ports ft601_data[4]]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22  [get_ports ft601_data[5]]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21  [get_ports ft601_data[6]]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18  [get_ports ft601_data[7]]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18  [get_ports ft601_data[8]]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20  [get_ports ft601_data[9]]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19  [get_ports ft601_data[10]]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20  [get_ports ft601_data[11]]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22  [get_ports ft601_data[12]]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21  [get_ports ft601_data[13]]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22  [get_ports ft601_data[14]]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20  [get_ports ft601_data[15]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15  [get_ports ft601_data[16]]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T21  [get_ports ft601_data[17]]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16  [get_ports ft601_data[18]]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20  [get_ports ft601_data[19]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17  [get_ports ft601_data[20]]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20  [get_ports ft601_data[21]]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21  [get_ports ft601_data[22]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22  [get_ports ft601_data[23]]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22  [get_ports ft601_data[24]]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21  [get_ports ft601_data[25]]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22  [get_ports ft601_data[26]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21  [get_ports ft601_data[27]]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports ft601_data[28]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports ft601_data[29]]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports ft601_data[30]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports ft601_data[31]]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17  [get_ports ft601_oe_n]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16  [get_ports ft601_rd_n]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports ft601_rxf_n]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB18 [get_ports ft601_siwu_n]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports ft601_txe_n]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19  [get_ports ft601_wr_n]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13  [get_ports ft601_rst_n]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports user_ld1_n]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports user_ld2_n]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports user_sw1_n]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports user_sw2_n]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports clk]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports ft601_clk]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports pcie_present]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports pcie_perst_n]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B13 [get_ports pcie_wake_n]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C9 [get_ports {pcie_rx_n[0]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports {pcie_rx_p[0]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {pcie_tx_n[0]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D7 [get_ports {pcie_tx_p[0]}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports pcie_clk_n]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports pcie_clk_p]
current_instance i_pcileech_pcie_a7/i_pcie_7x_0/inst
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/pl_phy_lnk_up_q_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/user_lnk_up_int_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/pl_received_hot_rst_q_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-7 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/bridge_reset_int_reg/PRE}}]
set_property src_info {type:SCOPED_XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-7 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/user_reset_int_reg/PRE}}]
set_property src_info {type:SCOPED_XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {NAME =~ {*/inst/user_lnk_up_mux_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async reset - safe to ignore" -scope -internal -from [get_pins -hier -filter {NAME =~ {*pr_loader_i/PIO_FPC_i/tandem_ctl_arb_i/user_app_rdy_gnt_reg/C}}] -to [get_pins -hier -filter {NAME =~ {*/inst/icap_pipeline_i/CSIB_OUT_reg/D}}]
set_property src_info {type:SCOPED_XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async reset - safe to ignore" -scope -internal -from [get_pins -hier -filter {NAME =~ {*pr_loader_i/PIO_FPC_i/tandem_ctl_arb_i/user_app_rdy_gnt_reg/C}}] -to [get_pins -hier -filter {NAME =~ {*/inst/icap_pipeline_i/I_OUT_reg[*]/D}}]
set_property src_info {type:SCOPED_XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async reset - safe to ignore" -scope -internal -from [get_pins -hier -filter {NAME =~ {*pr_loader_i/PIO_FPC_i/tandem_ctl_arb_i/user_app_rdy_gnt_reg/C}}] -to [get_pins -hier -filter {NAME =~ {*/inst/icap_pipeline_i/RDWRB_OUT_*/D}}]
set_property src_info {type:SCOPED_XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async reset - safe to ignore" -scope -internal -from [get_pins -hier -filter {NAME =~ {*pr_loader_i/PIO_FPC_i/PIO_EP_FPC_inst/data_transfer_i/eoc_1_fd_2dly_reg/C}}]  -to [get_pins -hier -filter {NAME =~ {*/pr_loader_i/PIO_FPC_i/PIO_EP_FPC_inst/data_transfer_i/end_config_reg/D}}]
