# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci
# IP: The module: 'drom_pcie_cfgspace_writemask' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'drom_pcie_cfgspace_writemask'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci
# IP: The module: 'drom_pcie_cfgspace_writemask' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeffr/OneDrive/Escritorio/SoundBlaster Full Emu/Captain75t/pcileech_enigma_x1/pcileech_enigma_x1.gen/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'drom_pcie_cfgspace_writemask'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
