# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci
# IP: The module: 'fifo_134_134_clk2_rxfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci
# IP: The module: 'fifo_134_134_clk2_rxfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/SoundBlaster/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_134_134_clk2_rxfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
