# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/pcileech_squirrel.xdc

# IP: ip/pcie_7x_0/pcie_7x_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] -quiet

# XDC: ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
