#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Script generated by Vivado on Wed Jul 24 21:37:35 -0500 2024
# SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : pcileech_enigma_x1_top.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : pcileech_enigma_x1_top.sh
#                pcileech_enigma_x1_top.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                pcileech_enigma_x1_top.sh [-reset_run]
#                pcileech_enigma_x1_top.sh [-reset_log]
#                pcileech_enigma_x1_top.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'pcileech_enigma_x1_top.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xpm -libname xil_defaultlib -libname fifo_generator_v13_2_10 -libname dist_mem_gen_v8_0_15 -libname blk_mem_gen_v8_4_8 -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xpm xil_defaultlib fifo_generator_v13_2_10 dist_mem_gen_v8_0_15 blk_mem_gen_v8_4_8)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "pcileech_enigma_x1_top.sh - Script generated by export_simulation (Vivado v2024.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./pcileech_enigma_x1_top.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_clock.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_eq.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_drp.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_rate.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_reset.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_sync.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gtp_pipe_rate.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gtp_pipe_drp.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gtp_pipe_reset.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_user.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pipe_wrapper.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_qpll_drp.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_qpll_reset.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_qpll_wrapper.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_rxeq_scan.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_top.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_core_top.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_rx_null_gen.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_rx_pipeline.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_rx.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_top.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_tx_pipeline.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_tx_thrtl_ctl.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_axi_basic_tx.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_7x.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_bram_7x.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_bram_top_7x.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_brams_7x.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_pipe_lane.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_pipe_misc.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie_pipe_pipeline.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gt_top.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gt_common.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gtp_cpllpd_ovrd.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gtx_cpllpd_ovrd.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gt_rx_valid_filter_7x.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_gt_wrapper.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0_pcie2_top.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/pcie_7x_0/sim/pcie_7x_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../ipstatic/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_10 $xmvhdl_opts \
  "../../ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../ipstatic/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/sim/fifo_134_134_clk2_rxfifo.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_1_1_clk2/sim/fifo_1_1_clk2.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_134_134_clk2/sim/fifo_134_134_clk2.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_43_43_clk2/sim/fifo_43_43_clk2.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_129_129_clk1/sim/fifo_129_129_clk1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work dist_mem_gen_v8_0_15 $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../ipstatic/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/drom_pcie_cfgspace_writemask/sim/drom_pcie_cfgspace_writemask.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_8 $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../ipstatic/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/bram_pcie_cfgspace/sim/bram_pcie_cfgspace.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_49_49_clk2/sim/fifo_49_49_clk2.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/bram_bar_zero4k/sim/bram_bar_zero4k.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/sim/fifo_141_141_clk1_bar_wr.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/sim/fifo_134_134_clk1_bar_rdrsp.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/sim/fifo_74_74_clk1_bar_rd1.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_32_32_clk2/sim/fifo_32_32_clk2.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_64_64/sim/fifo_64_64.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_64_64_clk1_fifocmd/sim/fifo_64_64_clk1_fifocmd.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_34_34/sim/fifo_34_34.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_256_32_clk2_comtx/sim/fifo_256_32_clk2_comtx.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_32_32_clk1_comtx/sim/fifo_32_32_clk1_comtx.v" \
  "../../../pcileech_enigma_x1.gen/sources_1/ip/fifo_64_64_clk2_comrx/sim/fifo_64_64_clk2_comrx.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../pcileech_enigma_x1.srcs/sources_1/imports/src" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_com.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_fifo.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_ft601.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_mux.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_pcie_a7.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_pcie_cfg_a7.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_pcie_tlp_a7.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_tlps128_bar_controller.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_tlps128_cfgspace_shadow.sv" \
  "../../../pcileech_enigma_x1.srcs/sources_1/imports/src/pcileech_enigma_x1_top.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.pcileech_enigma_x1_top xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.pcileech_enigma_x1_top -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path != "") && !(-e $lib_map_path) ]]; then
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log pcileech_enigma_x1_top_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./pcileech_enigma_x1_top.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: pcileech_enigma_x1_top.sh [-help]\n\
Usage: pcileech_enigma_x1_top.sh [-step]\n\
Usage: pcileech_enigma_x1_top.sh [-lib_map_path]\n\
Usage: pcileech_enigma_x1_top.sh [-reset_run]\n\
Usage: pcileech_enigma_x1_top.sh [-reset_log]\n\
Usage: pcileech_enigma_x1_top.sh [-keep_index]\n\
Usage: pcileech_enigma_x1_top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
